### ISSUE TITLE
Decrypt using user-supplied passphrase

### ISSUE THREAD

**Issue by stiang** [rubencaro/cipher#12]
This looks really nice, but I’m a little unsure if if can cover my use case. Perhaps you can shed some light (I’m fairly new to Elixir and not a crypto expert).

I’m building an HTTP-based API that will support authenticating using API keys/secrets, just like any other API. Unlike many, however, I will store only *encrypted* API secrets in the DB, which would then be decrypted on a request-by-request basis with a user-supplied passphrase in a header.

Does Cipher support such a dynamic use case? I notice you say that that the keyphrase needs to be set for Cipher to compile, so I’m guessing not?

**Comment by rubencaro** [comment]
Cipher does not support that explicitly. You could use it for that, but
that's not the intended use case.

I would recommend you to use something like jwt.io anyway. That is more
generic and widely supported.

Cheers

**Comment by stiang** [comment]
Thanks for the quick reply, I will investigate alternatives. Closing.
