### ISSUE TITLE
Tag versions, please?

### ISSUE THREAD

**Issue by nathanl** [rubencaro/cipher#13]
Hi! I'm using Cipher 1.3.1 and having a problem. It's probably my fault, but l want to look at the code to think through what's going on.

In situations like this, I look at the version of the library I have installed, then go to the Github project, browse to the tag for that version, and look at the code. This way I'm sure that the code I'm looking at matches what I'm running. (It also helps me be sure I'm looking at the README for the right version.)

It looks like you haven't created tags for some released versions, including 1.3.1. I cloned the repo and ran `git log -G 'version:'` to find commits with version bumps (changes to that line in `mix.exs`). It looks like  `4c8a38a91c6a9bb0d79da11ba1f1dacc41e179e0` should be tagged `1.3.1`.

Would you mind tagging this and future versions? In the Ruby world, `rake release` does this automatically - [here's a discussion on automating it in Elixir](https://groups.google.com/forum/#!topic/elixir-lang-core/xIjQQQtoKGY).

**Comment by rubencaro** [comment]
Sorry @nathanl , I never use tags anymore, so I just forgot about setting them. I assume I will forget again, so I recommend you check the autogenerated docs at https://hexdocs.pm/cipher. Now they have direct up to date references to the source they were generated from.

Thanks.

**Comment by nathanl** [comment]
Ah, OK. But I don't see a way there to look at docs for earlier versions, if that's what I happen to be running.

**Comment by rubencaro** [comment]
https://hex.pm/packages/cipher

There you can access to every version.

**Comment by nathanl** [comment]
OK, cool. Thanks for teaching me to use hex.pm. 😆
