### ISSUE TITLE
This library will result in insecure encryption

### ISSUE THREAD

**Issue by willbarrett** [rubencaro/cipher#19]
AES-CBC is insecure unless a randomly-generated, non-sequential IV is used. Taking the IV as a configuration param will result in insecure, easily brute-forceable encryption.

See this StackOverflow discussion for more information: https://stackoverflow.com/questions/2641720/for-aes-cbc-encryption-whats-the-importance-of-the-iv

**Comment by rubencaro** [comment]
@willbarrett you are right.

If you make a pull request adding that feature as an option I will accept it right away, of course. But the truth is `Cipher` is not really meant for that.

For applications that need any level of security I would recommend using a good implementation of JWT.

Thank you for your time anyway.

**Comment by quolpr** [comment]
Are you serious? For what `Cipher` is meant?

**Comment by rubencaro** [comment]
Yes I am :)

It's meant only to be compatible with some other crappy Ruby & Python & PHP preexistent code.

It's clearly stated in the main entry section of the readme.

**Comment by willbarrett** [comment]
May I recommend that this repository be close-sourced in that case? It would be good not to have insecure crypto implementations floating around.
