### ISSUE TITLE
Security issues - IV should be random

### ISSUE THREAD

**Issue by quolpr** [rubencaro/cipher#20]
http://www.cryptofails.com/post/70059609995/crypto-noobs-1-initialization-vectors

It is not secure to use IV as constant

**Comment by rubencaro** [comment]
@quolpr you are right.

If you make a pull request adding that feature as an option I will accept it right away, of course. But the truth is Cipher is not really meant for that.

For applications that need any level of security I would recommend using a good implementation of JWT.

Thank you for your time anyway.
