### ISSUE TITLE
mix test fails

### ISSUE THREAD

**Issue by munjal** [rubencaro/cipher#7]
When I try to run `mix test`

I get an error:
could not compile dependency :cipher, "mix compile" failed

== Compilation error on file lib/cipher.ex ==
*\* (ArgumentError) argument error
    :erlang.iolist_to_binary(nil)
    (crypto) crypto.erl:224: :crypto.hash/2
    lib/cipher/digest.ex:8: Cipher.Digest.generate_key/1
    lib/cipher.ex:9: (module)

I tried with Erlang 18.3 and 19.0
I've Elixir 1.3.2

I'd appreciate if you could assist. Thanks.

**Comment by munjal** [comment]
I found the issue: Cipher config was missing in test.exs.

I thought it might be helpful to anyone else!

**Comment by rubencaro** [comment]
Thanks!
