### ISSUE TITLE
Can't compile as a dependency

### ISSUE THREAD

**Issue by jeremyowensboggs** [rubencaro/cipher#8]
When including as a dependency, it won't compile
1) mix new throwaway
2) add {:cipher, "~> 1.2.3"} as a dependency in mix.exs
3) mix deps.get
4) mix deps.compile ends with
==> cipher
Compiling 4 files (.ex)

== Compilation error on file lib/cipher.ex ==
** (ArgumentError) argument error
    :erlang.iolist_to_binary(nil)
    (crypto) crypto.erl:225: :crypto.hash/2
    lib/cipher/digest.ex:8: Cipher.Digest.generate_key/1
    lib/cipher.ex:9: (module)

could not compile dependency :cipher, "mix compile" failed. You can recompile this dependency with "mix deps.compile cipher", update it with "mix deps.update cipher" or clean it with "mix deps.clean cipher"
---
never mind, saw the configuration required

**Comment by jeremyowensboggs** [comment]
Or, I could read the instructions, and the configuration as required 
config :cipher, keyphrase: "testiekeyphraseforcipher",
                ivphrase: "testieivphraseforcipher",
                magic_token: "magictoken"

**Comment by chalmagean** [comment]
I have it configured and I still get that error... did you fix this?

**Comment by rubencaro** [comment]
@chalmagean can you give the means to reproduce your situation?

**Comment by chalmagean** [comment]
@rubencaro I'll have to try again, I don't remember exactly how I got there

**Comment by rubencaro** [comment]
@chalmagean it's OK. I close this. Reopen if you get to reproduce it.
